name: Build binaries

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 2

    container:
      image: docker://devkitpro/devkitppc
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git Describe
        run: git describe --always --match \"tag\" --dirty

      - name: Compile
        run: |
          ./scripts/version.sh
          make -j2

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with: 
          name: rb3e-launcher-wii-debug
          path: |
            bin/launcher.dol
            bin/launcher.map
